### ISSUE TITLE
 options.prepare is not a function

### ISSUE THREAD

**Issue by Hretic** [checkly/puppeteer-recorder#54]
hi , im trying ti record browser activity on the server

her eis simplified version of my code
```

const puppeteer = require('puppeteer');
const { record } = require('puppeteer-recorder');
var path = 'C:\\wamp64\\www\\home_robot\\';

init_puppeteer();

const global_browser  ; 
async function init_puppeteer() {
        global_browser = await puppeteer.launch({headless: false , args: ['--no-sandbox', '--disable-setuid-sandbox']});

    check_login()
};


async function check_login()
{

    try {
        const page = await global_browser.newPage();
        await page.setViewport({width: 1000, height: 1100});
        await record({
            browser: global_browser, // Optional: a puppeteer Browser instance,
            page: page, // Optional: a puppeteer Page instance,
            output: path + 'output.webm',
            fps: 60,
            frames: 60 * 5, // 5 seconds at 60 fps
        });

        await page.goto('https://www.example.cob', {timeout: 60000});
        await page.close();
    }
    catch (e) {
        console.log(' LOGIN ERROR ---------------------');
        console.log(e);
    }
}

```

but when i run it i get this error
```


 LOGIN ERROR ---------------------
TypeError: options.prepare is not a function
    at module.exports.record (C:\wamp64\www\home_robot\node_modules\puppeteer-recorder\index.js:8:17)
    at check_login (C:\wamp64\www\home_robot\home.js:178:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)

```

**Comment by tnolet** [comment]
Hey @Hretic I think you are looking for this repo https://github.com/clipisode/puppeteer-recorder#readme

This repo is for a totally unrelated Chrome extension.
